// Generated by CoffeeScript 2.2.1
(function() {
  var Layout, React, Root, Route, ServerRenderer, createPage, createRoute, elem, layout, locals, models, website;

  React = require("react");

  models = require("../models");

  Route = require("react-router-dom").Route;

  ServerRenderer = require("./server").default;

  elem = function(tag, ...children) {
    return React.createElement(tag, {
      children: children
    });
  };

  Root = class Root extends React.Component {
    render() {
      return elem("html", elem("head", elem("title", `${this.props.page.title} | ${this.props.website.title}`)), elem("body", "%%%BODY%%%"));
    }

  };

  Layout = class Layout extends React.Component {
    render() {
      return elem("div", elem(this.props.page.body));
    }

  };

  layout = new models.Layout("test", Layout);

  createPage = function(url, title, date) {
    return new models.Page(title, "", url, layout, (function() {
      return elem("p", title);
    }), true, date, [], [], true);
  };

  createRoute = function(page) {
    return React.createElement(Route, {
      page: page,
      path: page.url,
      key: page.url,
      component: function() {
        return React.createElement(Layout, {
          page: page
        });
      }
    });
  };

  locals = {
    webpackStats: {
      compilation: {
        assets: {
          "bundle.css": {},
          "bundle.js": {}
        }
      }
    }
  };

  website = {
    title: "website.test"
  };

  describe("ServerRenderer", function() {
    var testedRenderer;
    testedRenderer = null;
    beforeEach(function() {
      return testedRenderer = new ServerRenderer(Root);
    });
    return it("renders single page", function() {
      var page, result, route;
      page = createPage("/", "Meeting", new Date("1954, Feb 20"));
      route = createRoute(page);
      result = testedRenderer.render(locals, website, [{page, route}]);
      (Object.keys(result)).should.eql(["/"]);
      return result["/"].should.equal("" + "<!DOCTYPE html>\n" + "<html>" + "<head><title>Meeting | website.test</title></head>" + "<body><div data-reactroot=\"\"><p>Meeting</p></div></body>" + "</html>");
    });
  });

}).call(this);

//# sourceMappingURL=server.spec.js.map
